config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :subscriptions do
      resource :customer, controller: "subscriptions/customer_details"
    end

    resources :products, as: :magazines do
      resources :issues, controller: "products/issues"
      match "issues/:id/ship", to: "products/issues#ship", via: :get, as: :issue_ship
      match "issues/:id/unship", to: "products/issues#unship", via: :get, as: :issue_unship
    end

    resources :users do
      member do
        get :subscriptions
      end
    end
  end
end

app/models/spree/issue.rb
class Spree::Issue < ActiveRecord::Base
  belongs_to :magazine, class_name: "Spree::Product"
  belongs_to :magazine_issue, class_name: "Spree::Product"
  has_many :shipped_issues

  delegate :subscriptions, to: :magazine

  validates :name,
            presence: true,
            unless: "magazine_issue.present?"

  scope :shipped, -> { where("shipped_at IS NOT NULL") }
  scope :unshipped, -> { where("shipped_at IS NULL") }

  scope :shipped, -> { where("shipped_at IS NOT NULL") }
  scope :unshipped, -> { where("shipped_at IS NULL") }

  def name
    magazine_issue.present? ? magazine_issue.name : read_attribute(:name)
  end

  def ship!
    subscriptions.eligible_for_shipping.each{ |s| s.ship!(self) }
    update_attribute(:shipped_at, Time.now)
  end

  def unship!
    Spree::Subscription.where(id: self.shipped_issues.pluck(:subscription_id)).each{ |s| s.unship!(self) }
    update_attribute(:shipped_at, nil)
  end

  def shipped?
    !shipped_at.nil?
  end
    
  def magazine
    # override getter method to include deleted products, as per https://github.com/radar/paranoia
    Spree::Product.unscoped { super }
  end
  
  def magazine_issue
    # override getter method to include deleted products, as per https://github.com/radar/paranoia
    Spree::Product.unscoped { super }
  end

end

app/controllers/spree/admin/products/issues_controller.rb
module Spree
  module Admin
    module Products
      class IssuesController < Spree::Admin::BaseController
        before_filter :load_magazine
        before_filter :load_issue, :only => [:show, :edit, :update, :ship, :unship]
        before_filter :load_products, :except => [:show, :index]

        def show
          if @issue.shipped?
            @product_subscriptions = Subscription.where(id: @issue.shipped_issues.pluck(:subscription_id)).includes(:ship_address)
          else
            @product_subscriptions = @magazine.subscriptions.eligible_for_shipping.includes(:ship_address)
          end
          respond_to do |format|
            format.html
            format.pdf do
              addresses_list = @product_subscriptions.map { |s| s.ship_address }
              labels = IssuePdf.new(addresses_list, view_context)
              send_data labels.document.render, filename: "#{@issue.name}.pdf", type: "application/pdf", disposition: "inline"
            end
          end
        end

        def index
          @issues = Issue.where(magazine_id: @magazine.id)
        end

        def update
          if @issue.update_attributes(issue_params)
            flash[:notice] = Spree.t('issue_updated')
            redirect_to admin_magazine_issue_path(@magazine, @issue)
          else
            flash[:error] = Spree.t(:issue_not_updated)
            render action: :edit
          end
        end

        def new
          @issue = @magazine.issues.build
        end

        def create
          if (new_issue = @magazine.issues.create(issue_params))
            flash[:notice] = Spree.t('issue_created')
            redirect_to admin_magazine_issue_path(@magazine, new_issue)
          else
            flash[:error] = Spree.t(:issue_not_created)
            render :new
          end
        end

        def destroy
          @issue = Issue.find(params[:id])
          @issue.destroy

          flash[:success] = Spree.t('issue_deleted')

          respond_with(@issue) do |format|
            format.html { redirect_to admin_magazine_issues_path(@issue.magazine) }
            format.js  { render_js_for_destroy }
          end
        end

        def ship
          if @issue.shipped?
            flash[:error]  = Spree.t('issue_not_shipped')
          else
            @issue.ship!
            flash[:notice]  = Spree.t('issue_shipped')
          end
          redirect_to admin_magazine_issues_path(@magazine, @issue)
        end
        
        def unship
          if @issue.shipped?
            @issue.unship!
            flash[:notice]  = Spree.t('issue_unshipped')
          else
            flash[:error]  = Spree.t('issue_not_shipped')
          end
          redirect_to admin_magazine_issues_path(@magazine)
        end

        private

        def load_magazine
          @magazine = Product.with_deleted.find_by_slug(params[:magazine_id])
          @product = @magazine # useful to display product_tab menu
        end

        def load_issue
          @issue = Issue.find(params[:id])
        end

        def load_products
          @products = Product.unsubscribable
        end

        def issue_params
          params.require(:issue).permit(:name, :published_at, :shipped_at, :magazine, :magazine_issue_id)
        end
      end
    end
  end
end

app/views/spree/admin/products/issues/_form.html.erb
<fieldset>
  <%= f.field_container :name do %>
    <%= f.label :name, "Issue Name (Optional)" %>
    <%= f.text_field :name, class: 'fullwidth' %>
  <% end %>

  <%= f.field_container :magazine_issue_id do %>
    <%= f.label :magazine_issue_id, Spree.t(:product) %>
    <%= f.collection_select(:magazine_issue_id, @products, :id, :name, { include_blank: true }, { class: 'select2 fullwidth' }) %>
  <% end %>
</fieldset>

app/views/spree/admin/products/issues/_magazine_issue.html.erb
<div class="clearfix magazine_issue">
  <%= product_image(product) %>
  <h2><%= Spree.t(:description) %></h2>
  <%= truncate(product.description, length: 400) %>
</div>

app/views/spree/admin/products/issues/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Issues' } %>

<%= csrf_meta_tags %>

<div data-hook="admin_product_issue_edit_header">
  <h2><%= Spree.t("editing_issue") %></h2>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @magazine } %>
</div>

<div data-hook="admin_product_issue_edit_form">
  <div id="issue-form-wrapper">
    <%= form_for [@magazine, @issue], url: admin_magazine_issue_url(@magazine, @issue) do |f| %>
      <%= render 'form', f: f  %>

      <p class="form-buttons" data-hook="buttons">
     	  <%= button Spree.t(:update) %>
      </p>
    <% end %>
  </div>
</div>

app/views/spree/admin/products/issues/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Issues' } %>

<% content_for :page_actions do %>
  <li id="new_issue_link">
    <%= button_link_to Spree.t(:new_issue), new_admin_magazine_issue_url(@magazine), { icon: 'plus', id: 'admin_new_issue' } %>
  </li>
<% end if can?(:create, Spree::Issue) %>

<h1><%= Spree.t(:listing_issues) %></h1>

<table class="index" id="listing_issues">
  <thead>
    <tr>
      <th data-hook="admin_issues_index_header_name"><%= Spree.t(:name, scope: 'activerecord.attributes.spree/issue') %></th>
      <th data-hook="admin_issues_index_header_shipped_at"><%= t(:shipped_at, scope: 'activerecord.attributes.spree/issue') %></th>
      <th data-hook="admin_issues_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td data-hook="admin_issues_index_row_name"><%= link_to issue.name, admin_magazine_issue_url(@magazine, issue) %></td>
        <td data-hook="admin_issues_index_row_shipped_at"><%= issue.shipped? ? issue.shipped_at.to_s(:db) : Spree.t(:issue_not_shipped) %></td>
        <td class="actions" data-hook="admin_issues_index_row_actions">
          <%= link_to_with_icon :truck, Spree.t(:ship), admin_magazine_issue_ship_path(@magazine, issue), {no_text: true, confirm: Spree.t(:confirm_ship)} if !issue.shipped? %>
          <%= link_to_with_icon :history, Spree.t(:unship), admin_magazine_issue_unship_path(@magazine, issue), {no_text: true, confirm: Spree.t(:confirm_unship)} if issue == @issues.shipped.order('shipped_at DESC').first %>
          <%= link_to_with_icon :edit,  Spree.t(:edit), edit_admin_magazine_issue_url(@magazine, issue), no_text: true, class: 'edit' if !issue.shipped? %>
          <%= link_to_with_icon :trash,  Spree.t(:delete), admin_magazine_issue_url(@magazine, issue), method: :delete, no_text: true if !issue.shipped? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/products/issues/new.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Issues' } %>

<%= csrf_meta_tags %>

<div data-hook="admin_product_issue_new_header">
  <h2><%= Spree.t("creating_issue") %></h2>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @magazine } %>
</div>

<div data-hook="admin_product_issue_new_form">
  <div id="issue-form-wrapper">
    <%= form_for [@magazine, @issue], url: admin_magazine_issues_path(@magazine), method: :post do |f| %>
      <%= render 'form', f: f  %>

      <p class="form-buttons" data-hook="buttons">
        <%= button Spree.t(:create) %>
		  </p>
    <% end %>
  </div>
</div>

app/views/spree/admin/products/issues/show.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Issues' } %>

<div data-hook="admin_product_issue_header">
  <h2><%= @issue.name %></h2>
</div>

<% if @issue.magazine_issue %>
  <%= render 'magazine_issue', product: @issue.magazine_issue %>
<% end %>

<div class="toolbar" data-hook="admin_issue_show_buttons">
  <%= button_link_to Spree.t(:ship), admin_magazine_issue_ship_path(@product, @issue), icon: :truck, confirm: Spree.t(:are_you_sure) if !@issue.shipped? %>
  <%= button_link_to Spree.t(:pdf), admin_magazine_issue_path(@product, @issue, format: :pdf), icon: 'file-pdf-o' %>
  <%= button_link_to Spree.t(:unship), admin_magazine_issue_unship_path(@magazine, @issue), icon: :history, confirm: Spree.t(:confirm_unship) if @issue == @issue.magazine.issues.shipped.order('shipped_at DESC').first %>
  <%= button_link_to Spree.t(:delete), admin_magazine_issue_url(@magazine, @issue), icon: :trash, method: :delete if !@issue.shipped? %>
</div>
<br class="clear">
<br>

<h1><%= @issue.shipped? ? Spree.t(:shipped_to) : Spree.t(:subscribed) %></h1>

<table class="index" id="subscriptions_listing">
  <thead data-hook="admin_subscriptions_index_headers">
    <th><%= Spree.t(:email) %></th>
    <th><%= Spree.t(:first_name) %></th>
    <th><%= Spree.t(:last_name) %></th>
    <th><%= Spree.t(:street_address) %></th>
    <th><%= Spree.t(:zip) %></th>
    <th><%= Spree.t(:city) %></th>
    <th><%= Spree.t(:state) %></th>
    <th><%= Spree.t(:phone) %></th>
  </thead>
  <tbody>
    <% @product_subscriptions.each do |subscription|%>
      <tr id="<%= spree_dom_id subscription %>" data-hook="admin_subscriptions_index_rows">
        <td><%= subscription.email %></td>
        <td><%= subscription.ship_address.firstname %></td>
        <td><%= subscription.ship_address.lastname %></td>
        <td>
          <%= subscription.ship_address.address1 %>
          <%= raw("</br>#{subscription.ship_address.address2}") if subscription.ship_address.address2.present? %>
        </td>
        <td><%= subscription.ship_address.zipcode %></td>
        <td><%= subscription.ship_address.city %></td>
        <td><%= subscription.ship_address.state_name %></td>
        <td><%= subscription.ship_address.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>