config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :subscriptions do
      resource :customer, controller: "subscriptions/customer_details"
    end

    resources :products, as: :magazines do
      resources :issues, controller: "products/issues"
      match "issues/:id/ship", to: "products/issues#ship", via: :get, as: :issue_ship
      match "issues/:id/unship", to: "products/issues#unship", via: :get, as: :issue_unship
    end

    resources :users do
      member do
        get :subscriptions
      end
    end
  end
end

app/views/spree/admin/shared/_subscription_address_form.html.erb
<table class="index">
  <thead>
    <tr data-hook="use_billing">
      <th colspan="8">
        <%= name %>
      </th>
    </tr>
  </thead>
  <tbody id="<%= name == Spree.t(:shipping_address) ? 'shipping' : 'billing' %>" data-hook="address_fields">
    <tr class="<%= name == Spree.t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :firstname, Spree.t(:first_name) + ':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :firstname %></td>
      <td class="lbl-col">
        <%= f.label :lastname, Spree.t(:last_name) + ':' %>
      </td>
      <td class="val-col" colspan="3"><%= f.text_field :lastname %></td>
    </tr>
    <% if Spree::Config[:company] %>
      <tr class="<%= name == Spree.t(:company) ? 'shipping-row' : 'billing-row' %>">
        <td class="lbl-col">  <%= f.label :company, Spree.t(:company) + ':' %> </td>
        <td class=colspan="7"> <%= f.text_field :company %> </td>
      </tr>
    <% end %>
    <tr class="<%= name == Spree.t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :address1, Spree.t(:street_address) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :address1, class: "fullwidth" %></td>
      <td class="lbl-col">
        <%= f.label :address2, Spree.t(:street_address_2) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :address2, class: "fullwidth" %></td>
    </tr>
    <tr class="<%= name == Spree.t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :city, Spree.t(:city) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :city %></td>
      <td class="lbl-col">
        <%= f.label :zipcode, Spree.t(:zip) + ':' %>
      </td>
      <td colspan="3"><%= f.text_field :zipcode, style: 'width: 100px;' %></td>
    </tr>
    <tr class="<%= name == Spree.t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :state_id, Spree.t(:state) + ':' %>
      </td>
      <td colspan="3">
        <span id="<%= name == Spree.t(:shipping_address) ? 's' : 'b' %>state">
          <%= f.text_field :state_name, style: "width:150px; display: #{f.object.country.states.empty? ? 'block' : 'none' };", disabled: !f.object.country.states.empty? %>
          <%= f.collection_select :state_id, f.object.country.states.sort, :id, :name, {include_blank: true}, {style: "width:150px; display: #{f.object.country.states.empty? ? 'none' : 'block' };", disabled: f.object.country.states.empty?} %>
        </span>
      </td>
      <td class="lbl-col">
        <%= f.label :country_id, Spree.t(:country) + ':' %>
      </td>
      <td colspan="3">
        <span id="<%= name == Spree.t(:shipping_address) ? 's' : 'b' %>country"><%= f.collection_select :country_id, available_countries, :id, :name, {}, {style: 'width: 150px;'} %></span>
      </td>
    </tr>
    <tr class="<%= name == Spree.t(:shipping_address) ? 'shipping-row' : 'billing-row' %>">
      <td class="lbl-col">
        <%= f.label :phone, Spree.t(:phone) + ':' %>
      </td>
      <td colspan="7"><%= f.text_field :phone %></td>
    </tr>
  </tbody>
</table>

<% content_for :head do %>
  <%= javascript_tag do -%>
    $(document).ready(function(){
    $('span#<%= name == Spree.t(:shipping_address) ? 's' : 'b' %>country select').change(function() { update_state('<%= name == Spree.t(:shipping_address) ? 's' : 'b' %>'); });
    });
  <% end -%>
<% end %>

app/views/spree/admin/shared/_subscription_tabs.html.erb
<h1><%= Spree.t(:subscription).titleize %> <%= @subscription.id %></h1>

<% content_for :sidebar do %>
  <div id="subscription_tab_summary" data-hook>
    <h3 id="subscription_id" data-hook><%= Spree.t(:subscription).titleize %> #<%= @subscription.id %></h3>
    <h5 id="subscription_status" data-hook><%= Spree.t(:status) %>: <%= Spree.t(@subscription.state, scope: :subscription_state) %></h5>
    <br class="clear" />
  </div>
  <br class="clear" />

  <ul class="sidebar" data-hook="admin_subscription_tabs">
      <li<%== ' class="active"' if current == 'Subscription Details' %>>
      <%= link_to Spree.t(:subscription_details), edit_admin_subscription_url(@subscription) %>
      </li>
      <li<%== ' class="active"' if current == 'Customer Details' %>>
      <%= link_to Spree.t(:customer_details), admin_subscription_customer_url(@subscription) %>
      </li>
    </ul>
<% end %>

app/views/spree/admin/shared/_subscriptions_sidebar_menu.html.erb
<% if can? :admin, Spree::Subscription %>
  <ul class="nav nav-sidebar">
    <%= tab Spree::Subscription, url: spree.admin_subscriptions_url, icon: 'calendar', label: 'subscriptions' %>
  </ul>
<% end %>